combinations/Ccombinations/urls.py
from django.urls import path
from .views import color_create, color_list,voiture_list,chercher_voiture,recherche_voiture

urlpatterns = [
    path('colors/create/', color_create, name='color_create'),
    path('colors/', color_list, name='color_list'),
    path('colors/a/', voiture_list, name='voiture_list'),
    path('colors/voiture/', chercher_voiture,name="chercher_voiture"),
    path('colors/recherche/', recherche_voiture,name="recherche_voiture"),



 
]

combinations/combinations/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ccombinations.urls')),

]

combinations/Ccombinations/models.py
from django.db import models

class Color(models.Model):
    name = models.CharField(max_length=50)
    hex_code = models.CharField(max_length=7, unique=True)


    def __str__(self):
        return self.name
class Marque(models.Model):
    nom = models.CharField(max_length=100)

    def __str__(self):
        return self.nom
class Voiture(models.Model):
    nom = models.CharField(max_length=100)
    annee_fabrication = models.IntegerField()
    marque = models.ForeignKey(Marque, on_delete=models.CASCADE)
    code = models.ManyToManyField(Color, related_name='voitures')
    def __str__(self):
        return self.nom
class FormulePeinture(models.Model):
    code_couleur = models.ForeignKey(Color, on_delete=models.CASCADE)
    base_teint1 = models.CharField(max_length=50)
    quantite_base_teint1 = models.FloatField()
    base_teint2 = models.CharField(max_length=50, blank=True, null=True)
    quantite_base_teint2 = models.FloatField(blank=True, null=True)
    base_teint3 = models.CharField(max_length=50, blank=True, null=True)
    quantite_base_teint3 = models.FloatField(blank=True, null=True)

combinations/Ccombinations/forms.py
from django import forms
from .models import Color,Voiture,FormulePeinture,Marque

class ColorForm(forms.ModelForm):
    class Meta:
        model = Color
        color=forms.ModelChoiceField(queryset=Color.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
        fields = ['name', 'hex_code']

class VoitureForm(forms.ModelForm):
    class Meta:
        model = Voiture
        fields=['nom','annee_fabrication','marque'] 

class FormulePeintureForm(forms.ModelForm):
    class Meta:
        model=FormulePeinture
        fields=['code_couleur','base_teint1','quantite_base_teint1','base_teint2','quantite_base_teint2',
         'base_teint3', 'quantite_base_teint3']        

class MarqueForm(forms.ModelForm):
    class Meta:
        model=Marque
        fields=['nom']

combinations/Ccombinations/views.py
from django.shortcuts import render, redirect
from .models import Color,Voiture,FormulePeinture,Marque
from .forms import ColorForm,VoitureForm,FormulePeintureForm,MarqueForm

def color_create(request):

    if request.method == 'POST':
        form = ColorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('color_list')
    else:
        form = ColorForm()
    return render(request, 'color_create.php', {'form': form})



def color_list(request):
    colors = Color.objects.all()
    return render(request, 'color_list.php', {'colors': colors})

def voiture_create(request):
    if request.method == 'POST':
        form = VoitureForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('voiture_list')
    else:
        form = ColorForm()
    return render(request, 'color_create.php', {'form': form})
def voiture_list(request):
    voitures = Voiture.objects.all()
    return render(request, 'color_list.php', {'voitures': voitures})


def chercher_voiture(request):
    if request.method == 'POST':
        hex_code = request.POST.get('hex_code', '')
        nom = request.POST.get('nom', '')
        voiture = Voiture.objects.filter(nom__iexact=nom).first()
        couleur = Color.objects.filter(hex_code__iexact=hex_code).first()
        formule_peinture= None
        formule_peinture1=None
        if voiture is not None and couleur is not None:
            formule_peinture = FormulePeinture.objects.get(code_couleur=voiture.code)
        elif voiture:
            formule_peinture = FormulePeinture.objects.get(code_couleur=voiture.code)
        elif couleur:
            formule_peinture1=FormulePeinture.objects.filter(code_couleur=couleur.id)






        return render(request, 'chercher_voiture.html',{'couleur':couleur,'voiture':voiture,'formule_peinture1': formule_peinture1,'formule_peinture': formule_peinture})
    else:
        return render(request, 'chercher_voiture.html')    




def recherche_voiture(request):
    if request.method == 'POST':
        nom_voiture = request.POST.get('nom')
        code_couleur = request.POST.get('hex_code')
        marque_voiture = request.POST.get('nom')
        if nom_voiture and code_couleur:
            voitures = Voiture.objects.filter(nom__icontains=nom_voiture, code__hex_code__icontains=code_couleur)
            couleur_cherchee = Color.objects.filter(hex_code=code_couleur).first()
            marques = Marque.objects.filter(nom=marque_voiture).first()
        elif nom_voiture:
            voitures = Voiture.objects.filter(nom__icontains=nom_voiture)
            couleur_cherchee = Color.objects.filter(hex_code=code_couleur).first()

        elif code_couleur:
            voitures = Voiture.objects.filter(code__hex_code__icontains=code_couleur)
            couleur_cherchee = Color.objects.filter(hex_code=code_couleur).first()

        else:
            voitures = []
            couleur_cherchee = None

        context = {'voitures': voitures, 'nom_voiture': nom_voiture,'couleur_cherchee': couleur_cherchee}
        return render(request, 'recherche_voiture.html', context)

    return render(request, 'recherche_voiture.html')





def get_formule_peinture(self):
        formule = FormulePeinture.objects.get( code=self.code)
        return formule        

combinations/Ccombinations/templates/chercher_voiture.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Chercher une voiture</title>
  </head>
  <body>
    <h1>Chercher une voiture</h1>
    <form method="post">
      {% csrf_token %}
      <label for="nom">Nom de la voiture :</label>
      <input type="text" id="nom" name="nom" >
      <input type="text" id="hex_code" name="hex_code" >
      <button type="submit">Chercher</button>
    </form>


    
    {% if voiture %}
    
    <h2>Résultats de la recherche :</h2>
    <p>Nom : {{ voiture.nom }}</p>
    <p>Année de fabrication : {{ voiture.annee_fabrication }}</p>
    <p>Marque : {{ voiture.marque.nom }}</p>
    <div style= "background-color:  {{  voiture.code.hex_code  }} ;">couleur : {{ voiture.code.name }}</div>
    <p>Composition </p>
    <ul>
      

      <table style="width: 250px; height: 250px;">
        <tr>
            <th>couleur</th>
            <th>quantité</th>

        </tr>
        <tr>
            <td style="background-color:  {{  formule_peinture.base_teint1   }} "></td>
            <td>{{ formule_peinture.quantite_base_teint1 }} g</td>
        </tr>
        <tr>
        {% if formule_peinture.base_teint2 %}
          <td  style="background-color:{{ formule_peinture.base_teint2 }}">:</td>
          <td> {{ formule_peinture.quantite_base_teint2 }} g</td>
        {% endif %}
        {% if formule_peinture.base_teint3 %}
          <td>{{ formule_peinture.base_teint3 }}: {{ formule_peinture.quantite_base_teint3 }}</td>
        {% endif %}

        </ul>
        </tr>
      </table>

    {% endif %}
     <ul>
      {% if couleur %}
    
    <h2>Résultats de la recherche :</h2>
    <p>Nom : {{ couleur.name }}</p>
   </ul>
   {% if formule_peinture1 %}
   <h2>Formules de peinture :</h2>
   <ul>
       {% for formule_peinture in formule_peinture1 %}
           <li>Base teint 1: {{ formule_peinture.base_teint1 }} ({{ formule_peinture.quantite_base_teint1 }})</li>
           {% if formule_peinture.base_teint2 %}
               <li>Base teint 2: {{ formule_peinture.base_teint2 }} ({{ formule_peinture.quantite_base_teint2 }})</li>
           {% endif %}
           {% if formule_peinture.base_teint3 %}
               <li>Base teint 3: {{ formule_peinture.base_teint3 }} ({{ formule_peinture.quantite_base_teint3 }})</li>
           {% endif %}
       {% endfor %}
   </ul>
   {% endif %}

{% endif %}





















  </body>
</html>

combinations/Ccombinations/templates/recherche_voiture.html
    <!DOCTYPE html>
    <html>
    <head>
      <title>Rechercher une voiture</title>
      <!-- Add Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    </head>
    <body>
    
    <div class="container">
      <h1>Chercher une couleur</h1>
      <form method="post" action="{% url 'recherche_voiture' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="marque">Marque voiture :</label>
            <input type="text" class="form-control" id="nom" name="nom">
          </div>
        <div class="form-group">
          <label for="nom">Nom de la voiture :</label>
          <input type="text" class="form-control" id="nom" name="nom">
        </div>
        <div class="form-group">
          <label for="hex_code">Code couleur :</label>
          <input type="text" class="form-control" id="hex_code" name="hex_code">
        </div>
       
        <button type="submit" class="btn btn-primary">Chercher</button>
      </form>
    
      <!-- Results -->
      {% if couleur_cherchee %}
        <h2>Résultats de la recherche :</h2>
        <div class="card" style="margin-bottom: 50px;">
            {{ couleur_cherchee.name }} 
            <div style="background-color: {{ couleur_cherchee.hex_code }} ; width: 100px; height: 50px;">
              </div> 

        </div>

       
        <table class="table table-bordered">
            <thead>
                <th>Base de teint</th>
                <th>Quantité en grammes</th>
            </thead>
            <tbody>
                <tr>
              {% for formule_peinture in couleur_cherchee.formulepeinture_set.all %}
                 <td style="background-color : {{ formule_peinture.base_teint1 }}; width:250px"></td>
                 <td>{{ formule_peinture.quantite_base_teint1 }} g</td>
                 <tr>
                    {% if formule_peinture.base_teint2 %}
                    <td style="background-color : {{ formule_peinture.base_teint2 }}; width:250px"></td>
                    <td>{{ formule_peinture.quantite_base_teint2 }} g</td>
                    {% endif %}
                 </tr>
                 <tr>
                {% if formule_peinture.base_teint3 %}
                  <td>{{ formule_peinture.base_teint3 }} ({{ formule_peinture.quantite_base_teint3 }})</td>
                {% endif %}
                 </tr>  
                </tr>
               {% endfor %} 
            </tbody>
        </table>





        {% elif voitures %}
        <h2>Résultats de la recherche :</h2>
        <ul>
          {% for voiture in voitures %}
            <li>
              <div class="card" style="height: 40px;">Nom de voiture: {{ voiture.nom }}</div>
              <div class="card" style="height: 40px;">Année de fabrication : {{ voiture.annee_fabrication }}</div>
              <div class="card" style="height: 40px;">Marque : {{ voiture.marque.nom }}</div>
              <div style="height: 40px;">Couleurs de la voiture:</div>
              <ul>
                {% for couleur in voiture.code.all %}
                  <div class="card" style="margin-bottom: 50px;">
                    {{ couleur.name }} 
                    <div style="background-color: {{ couleur.hex_code }} ; width: 100px; height: 50px;">
                      </div> 
        
                </div>
                <div class="card">Formule de Couleur</div>
                  <table class="table table-bordered">
                    <thead>
                        <th>Base de teint</th>
                        <th>Quantité en grammes</th>
                    </thead>
                    <tbody>
                        <tr>
                      {% for formule_peinture in couleur.formulepeinture_set.all %}
                         <td style="background-color : {{ formule_peinture.base_teint1 }}; width:250px"></td>
                         <td>{{ formule_peinture.quantite_base_teint1 }} g</td>
                         <tr>
                            {% if formule_peinture.base_teint2 %}
                            <td style="background-color : {{ formule_peinture.base_teint2 }}; width:250px"></td>
                            <td>{{ formule_peinture.quantite_base_teint2 }} g</td>
                            {% endif %}
                         </tr>
                         <tr>
                        {% if formule_peinture.base_teint3 %}
                          <td>{{ formule_peinture.base_teint3 }} ({{ formule_peinture.quantite_base_teint3 }})</td>
                        {% endif %}
                         </tr>  
                        </tr>
                       {% endfor %} 
                    </tbody>
                </table>

                  
                {% endfor %}
              </ul>
            </li>
          {% empty %}
            <p>Pas de couleur correspondante.</p>
          {% endfor %}
        </ul>
      {% else %}
      {% endif %}

</div>
<!-- Add Bootstrap JS (optional) -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>